In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.txt",header=None)

In [3]:
#df=pd.DataFrame(df)

In [4]:
df.columns=["Sentence"]
df

                                                Sentence
0                        i didnt feel humiliated;sadness
1      i can go from feeling so hopeless to so damned...
2      im grabbing a minute to post i feel greedy wro...
3      i am ever feeling nostalgic about the fireplac...
4                             i am feeling grouchy;anger
...                                                  ...
15995  i just had a very brief time in the beanbag an...
15996  i am now turning and i feel pathetic that i am...
15997                 i feel strong and good overall;joy
15998  i feel like this was such a rude comment and i...
15999  i know a lot but i feel so stupid because i ca...

[16000 rows x 1 columns]

In [5]:
df[["Sentence","Emotion"]]=df["Sentence"].str.split(';',n=1,expand=True)

In [6]:
df

                                                Sentence  Emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [7]:
df.isnull().sum()

Sentence    0
Emotion     0
dtype: int64

In [8]:
indep=df["Sentence"]
dep=df["Emotion"]

In [9]:
dep

0        sadness
1        sadness
2          anger
3           love
4          anger
          ...
15995    sadness
15996    sadness
15997        joy
15998      anger
15999    sadness
Name: Emotion, Length: 16000, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.33,random_state=53)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer as cv
counter=cv()
xtrain_c=counter.fit_transform(x_train)
xtest_c=counter.transform(x_test)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv1=CountVectorizer(stop_words='english')
ytrain=cv1.fit_transform(y_train)
ytest=cv1.transform(y_test)

In [15]:
a=cv1.inverse_transform(ytest)

In [16]:
a

[array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['fear'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['surprise'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['joy'], dtype='<U8'),
 array(['sadness'], dtype='<U8'),
 array(['anger'], dtype='<U8'),
 array(['love'], dtype='<U8'),
 array(['anger'], dtype='<U8'),

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
xtrain_c=tfidf.fit_transform(x_train)
xtest_c=tfidf.transform(x_test)

In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer
hashvec=HashingVectorizer()
xtrain_c=hashvec.fit_transform(x_train)
xtest_c=hashvec.transform(x_test)

In [ ]:
xtrain_c

In [ ]:
xtrain_c.shape

In [ ]:
type(xtrain_c)

In [ ]:
y_train.shape

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(xtrain_c,y_train)

In [ ]:
from sklearn.metrics import r2_score,accuracy_score,classification_report
ypred=model.predict(xtest_c)

In [ ]:
ypred

In [ ]:
accuracy_score(y_test,ypred)

In [ ]:
report=classification_report(y_test,ypred)
print(report)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(xtrain_c,y_train)

In [ ]:
from sklearn.metrics import r2_score,accuracy_score,classification_report
ypred=rf.predict(xtest_c)
print(accuracy_score(y_test,ypred))
report=classification_report(y_test,ypred)
print(report)

In [ ]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(xtrain_c,y_train)

In [ ]:
ypred=sv.predict(xtest_c)
print(accuracy_score(y_test,ypred))
report=classification_report(y_test,ypred)
print(report)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain_c,y_train)

In [ ]:
ypred=lr.predict(xtest_c)
print(accuracy_score(y_test,ypred))
report=classification_report(y_test,ypred)
print(report)

In [13]:
#pip install nltk

In [14]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\jerli\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [15]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia=SentimentIntensityAnalyzer()

In [16]:
df["Sentence"][1]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [17]:
testing=sia.polarity_scores(df["Sentence"][1])
testing

{'neg': 0.227, 'neu': 0.503, 'pos': 0.271, 'compound': 0.0821}

In [18]:
testing['neg']

0.227

In [19]:
for i in range(10):
    psc=sia.polarity_scores(df["Sentence"][i])
    print(psc)

{'neg': 0.0, 'neu': 0.496, 'pos': 0.504, 'compound': 0.2584}
{'neg': 0.227, 'neu': 0.503, 'pos': 0.271, 'compound': 0.0821}
{'neg': 0.474, 'neu': 0.526, 'pos': 0.0, 'compound': -0.6597}
{'neg': 0.0, 'neu': 0.909, 'pos': 0.091, 'compound': 0.128}
{'neg': 0.537, 'neu': 0.185, 'pos': 0.278, 'compound': -0.34}
{'neg': 0.315, 'neu': 0.577, 'pos': 0.108, 'compound': -0.4346}
{'neg': 0.061, 'neu': 0.596, 'pos': 0.342, 'compound': 0.8407}
{'neg': 0.29, 'neu': 0.71, 'pos': 0.0, 'compound': -0.5994}
{'neg': 0.0, 'neu': 0.64, 'pos': 0.36, 'compound': 0.743}
{'neg': 0.0, 'neu': 0.426, 'pos': 0.574, 'compound': 0.4019}

In [57]:
data=df
def sentiment(data,text):
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    sia=SentimentIntensityAnalyzer()
    score_dict=data[text].apply(lambda x: sia.polarity_scores(x))
    data["Neg"]=data[text].apply(lambda x: sia.polarity_scores(x)['neg'])
    data["Neutral"]=data[text].apply(lambda x: sia.polarity_scores(x)['neu'])
    data["Positive"]=data[text].apply(lambda x: sia.polarity_scores(x)['pos'])
    data["Compound"]=data[text].apply(lambda x: sia.polarity_scores(x)['compound'])
    data["Sentiment"]=data["Compound"].apply(lambda y: 'Positive' if y>0 else 'Negative' if y<0 else 'Neutral')
    return score_dict,data

In [58]:
score_dict,data=sentiment(df,"Sentence")

In [59]:
data

,Sentence,Emotion,Neg,Neutral,Positive,Compound,Sentiment
0,i didnt feel humiliated,sadness,0.000,0.496,0.504,0.2584,Positive
1,i can go from feeling so hopeless to so damned...,sadness,0.227,0.503,0.271,0.0821,Positive
2,im grabbing a minute to post i feel greedy wrong,anger,0.474,0.526,0.000,-0.6597,Negative
3,i am ever feeling nostalgic about the fireplac...,love,0.000,0.909,0.091,0.1280,Positive
4,i am feeling grouchy,anger,0.537,0.185,0.278,-0.3400,Negative
...,...,...,...,...,...,...,...
15995,i just had a very brief time in the beanbag an...,sadness,0.126,0.762,0.112,-0.0772,Negative
15996,i am now turning and i feel pathetic that i am...,sadness,0.198,0.802,0.000,-0.5719,Negative
15997,i feel strong and good overall,joy,0.000,0.326,0.674,0.7351,Positive
15998,i feel like this was such a rude comment and i...,anger,0.182,0.485,0.333,0.3612,Positive
15999,i know a lot but i feel so stupid because i ca...,sadness,0.377,0.623,0.000,-0.7935,Negative

In [60]:
data[data["Sentiment"].str.contains('Neutral')]

,Sentence,Emotion,Neg,Neutral,Positive,Compound,Sentiment
13,i feel low energy i m just thirsty,sadness,0.292,0.417,0.292,0.0,Neutral
48,on a boat trip to denmark,joy,0.000,1.000,0.000,0.0,Neutral
120,i had begun to feel apprehensive when thick bl...,fear,0.000,1.000,0.000,0.0,Neutral
166,i still feel groggy but i have to get up to do...,sadness,0.000,1.000,0.000,0.0,Neutral
392,i feel like im putting an innocent man on deat...,joy,0.247,0.443,0.310,0.0,Neutral
...,...,...,...,...,...,...,...
15773,i feel the cold terrribly,anger,0.000,1.000,0.000,0.0,Neutral
15797,ill try to figure out calories and see how muc...,joy,0.136,0.728,0.136,0.0,Neutral
15862,i went to sleep friday i was feeling relieved ...,joy,0.114,0.735,0.151,0.0,Neutral
15883,i like them cause i can take or of one if i am...,sadness,0.124,0.708,0.168,-0.0,Neutral
15955,i shouldnt feel altogether mellow,joy,0.000,1.000,0.000,0.0,Neutral